### PR TITLE
Pull request 3 to master

### PR DESCRIPTION
**Pull request by MargaritaKrutikova**

### CODE REVIEW

**Comment by MargaritaKrutikova** [comment]
retest this please

**Comment by MargaretKrutikova** [comment]
retest this please

**Comment by MargaretKrutikova** [comment]
Looks good

**Comment by MargaretKrutikova** [comment]
Looks good

**Comment by MargaritaKrutikova** [comment]
test this please

**Comment by MargaretKrutikova** [comment]
Looks good

**Comment by MargaritaKrutikova** [comment]
test this please

**Comment by MargaretKrutikova** [comment]
Looks good

**Pull request merged**
